### ISSUE TITLE
Binary in Nuget cannot work in WP8.1 simulator

### ISSUE THREAD

**Issue by shadowglen** [neuecc/AsyncOAuth#14]
An exception is thown when using AsyncOAuth:

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Threading.Tasks, Version=1.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Threading.Tasks, Version=1.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at AsyncOAuth.OAuthAuthorizer.GetTokenResponse[T](String url, OAuthMessageHandler handler, HttpContent postValue, Func`3 tokenFactory)
   at AsyncOAuth.OAuthAuthorizer.GetRequestToken(String requestTokenUrl, IEnumerable`1 parameters, HttpContent postValue)

**Comment by jonnymunday** [comment]
I'm getting the same error on WP8.1 simulator.

**Comment by LexZhukov** [comment]
I'm getting the same error on my WP8.1 simulator.
